/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import estoque.EstoqueView;
import estoque.Produto;
import estoque.ProdutoDao;
import estoque.ProdutoView;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class TelaListagem extends javax.swing.JPanel {

    /**
     * Creates new form TelaListagem
     */
    public TelaListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContatos = new javax.swing.JTable();
        bntListar = new javax.swing.JButton();
        btnConsultarNome = new javax.swing.JToggleButton();
        txtConsultarNome = new javax.swing.JTextField();

        jTableContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "QTD DE ESTOQUE", "QTD DE ESTOQUE MINIMO", "UNIDADE DE MEDIDA", "VALOR COMPRA", "VALOR VENDA"
            }
        ));
        jScrollPane1.setViewportView(jTableContatos);

        bntListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacegrafica/pesquisar.jpg"))); // NOI18N
        bntListar.setText("LISTAR");
        bntListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntListarActionPerformed(evt);
            }
        });

        btnConsultarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacegrafica/pesquisar.jpg"))); // NOI18N
        btnConsultarNome.setText("CONSULTAR NOME:");
        btnConsultarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bntListar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnConsultarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsultarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 119, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntListar)
                    .addComponent(btnConsultarNome)
                    .addComponent(txtConsultarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListarActionPerformed
        // TODO add your handling code here:
        
        try {
            
           ProdutoDao produto = new ProdutoDao();
           Produto pr = new Produto();
           ProdutoView pw = new ProdutoView();
         
           
        
            ArrayList dados = produto.listar();
            DefaultTableModel model =  (DefaultTableModel) jTableContatos.getModel();
            model.setNumRows(0);
            for(int pos=0;pos<dados.size();pos++){
            String[] saida= new String[7];//novo
            Produto aux = (Produto)(dados.get(pos));//novo
            
           // String conversao = pr.setQtdEstoque(Double.parseDouble(aux.getQtdEstoque()));
            
            saida[0]= aux.getCodigo();//novo
            saida[1] = aux.getNome();
            saida[2] = Double.toString(aux.getQtdEstoque()) ;//novo
            saida[3] = Double.toString(aux.getQtdEstoqueMin());//novo
            saida[4] = aux.getUnidadeMedida();
            saida[5] = Double.toString(aux.getValorCompra());
            saida[6] = Double.toString(aux.getValorVenda());
            //Incluir nova linha na Tabela
            model.addRow(saida);//novo
        }

            
        } catch (Exception erro) {
            //JOptionPane.showMessageDialog(rootPane, erro.getMessage());
             System.out.println(erro.getMessage());
        }
    }//GEN-LAST:event_bntListarActionPerformed

    private void btnConsultarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarNomeActionPerformed
        // TODO add your handling code here:
        
        ProdutoDao p = new ProdutoDao();
            Produto pr = new Produto();
           try {
            
               String dados = txtConsultarNome.getText();
                Produto dados1 = p.consultar(dados);
            
            
            DefaultTableModel model =  (DefaultTableModel) jTableContatos.getModel();
            model.setNumRows(0);
            Produto aux = (Produto)(dados1);
         
            
            String [] saida = new String[7];
            saida[0] = aux.getCodigo();
            saida[1] = aux.getNome();
             saida[2] = Double.toString(aux.getQtdEstoque()) ;//novo
            saida[3] = Double.toString(aux.getQtdEstoqueMin());//novo
            saida[4] = aux.getUnidadeMedida();
            saida[5] = Double.toString(aux.getValorCompra());
            saida[6] = Double.toString(aux.getValorVenda());
            model.addRow(saida);
               
        } catch (Exception erro) {
            //JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            System.out.println(erro.getMessage());
        }
    }//GEN-LAST:event_btnConsultarNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntListar;
    private javax.swing.JToggleButton btnConsultarNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableContatos;
    private javax.swing.JTextField txtConsultarNome;
    // End of variables declaration//GEN-END:variables
}
