/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import estoque.EstoqueView;
import estoque.Produto;
import estoque.ProdutoDao;
import estoque.ProdutoView;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class TelaAlterar extends javax.swing.JPanel {

    /**
     * Creates new form TelaAlterar
     */
    public TelaAlterar() {
        initComponents();
    }

    Produto   pr ;
    ProdutoDao p = new ProdutoDao();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUnidadeDeMedida1 = new javax.swing.JTextField();
        txtValorCompra1 = new javax.swing.JTextField();
        txtCodigo1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorVenda1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQtdEstoqueMinimo1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQtdEmEstoque1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnConsultarAlt = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtNomeConsulta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        txtUnidadeDeMedida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadeDeMedida1ActionPerformed(evt);
            }
        });

        txtValorCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCompra1ActionPerformed(evt);
            }
        });

        txtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor Venda:");

        jLabel2.setText("Código");

        txtValorVenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorVenda1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Quantidade em Estoque Minimo");

        txtQtdEstoqueMinimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdEstoqueMinimo1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade em Estoque:");

        jLabel5.setText("Unidade de Medida:");

        txtQtdEmEstoque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdEmEstoque1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Valor Compra:");

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacegrafica/alterar.jpg"))); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConsultarAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacegrafica/pesquisar.jpg"))); // NOI18N
        btnConsultarAlt.setText("CONSULTAR");
        btnConsultarAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAltActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacegrafica/excluir.jpg"))); // NOI18N
        jToggleButton1.setText("DELETAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQtdEmEstoque1)
                                .addGap(52, 52, 52))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValorCompra1)
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorVenda1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(475, 475, 475))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQtdEstoqueMinimo1)
                                .addGap(480, 480, 480))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtUnidadeDeMedida1)
                                            .addGap(34, 34, 34)))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNomeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToggleButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(btnConsultarAlt)))))
                        .addGap(261, 261, 261))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarAlt))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidadeDeMedida1)
                    .addComponent(txtNomeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdEmEstoque1)
                    .addComponent(txtValorVenda1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorCompra1)
                    .addComponent(txtQtdEstoqueMinimo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void txtUnidadeDeMedida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadeDeMedida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadeDeMedida1ActionPerformed

    private void txtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo1ActionPerformed

    private void txtQtdEmEstoque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdEmEstoque1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdEmEstoque1ActionPerformed

    private void txtValorVenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorVenda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorVenda1ActionPerformed

    private void txtValorCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCompra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompra1ActionPerformed

    private void txtQtdEstoqueMinimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdEstoqueMinimo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdEstoqueMinimo1ActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
                   
                    
                    
                    try {
                      pr.setNome(txtNome1.getText());
                      pr.setCodigo(txtCodigo1.getText());
                      
                      
                    
                       String nome = txtNome1.getText();
                       String nome1 = txtNomeConsulta.getText();
                       p.alterar(pr);
                       
                       JOptionPane.showMessageDialog(txtNome1, "Foi Alterado o nome com sucesso");
                       txtNome1.setText("");
                       txtCodigo1.setText("");
                       txtQtdEmEstoque1.setText("");
                       txtQtdEstoqueMinimo1.setText("");
                       txtValorCompra1.setText("");
                       txtValorVenda1.setText("");
                       txtNomeConsulta.setText("");
                       txtUnidadeDeMedida1.setText("");
                                 
                                 
        } catch (Exception error) {
            System.out.println(error.getMessage());
        }

        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAltActionPerformed
   
        try {
            
            
            String dados = txtNome1.getText();
            pr = p.consultar(dados);
            
             
          txtNome1.setText(pr.getNome());
   
          txtNomeConsulta.setText(pr.getNome());
          String codigo = pr.getCodigo();
          txtCodigo1.setText(codigo);
          String unidmedida = pr.getUnidadeMedida();
          txtUnidadeDeMedida1.setText(unidmedida);
          String qtdestoque = Double.toString(pr.getQtdEstoque());
          txtQtdEmEstoque1.setText(qtdestoque);
          String valorvenda = Double.toString(pr.getValorVenda());
          txtValorVenda1.setText(valorvenda);
          String valorcompra = Double.toString(pr.getValorCompra());
          txtValorCompra1.setText(valorcompra);
          String qtdEstoqueMinimo = Double.toString(pr.getQtdEstoqueMin());
          txtQtdEstoqueMinimo1.setText(qtdEstoqueMinimo);

        } catch (Exception error) {
            System.out.println(error.getMessage());
        }
        
    }//GEN-LAST:event_btnConsultarAltActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        try {
            
            String nome = txtNome1.getText();
            p.deletar(nome);
            
            JOptionPane.showMessageDialog(txtNome1, "Foi deletado com sucesso");
            
            txtNome1.setText("");
            txtQtdEmEstoque1.setText("");
            txtQtdEstoqueMinimo1.setText("");
            txtUnidadeDeMedida1.setText("");
            txtValorCompra1.setText("");
            txtValorVenda1.setText("");
            txtNomeConsulta.setText("");
            txtValorCompra1.setText("");
            txtCodigo1.setText("");
        } catch (Exception eroor) {
            System.out.println(eroor.getMessage());
        }
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultarAlt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNomeConsulta;
    private javax.swing.JTextField txtQtdEmEstoque1;
    private javax.swing.JTextField txtQtdEstoqueMinimo1;
    private javax.swing.JTextField txtUnidadeDeMedida1;
    private javax.swing.JTextField txtValorCompra1;
    private javax.swing.JTextField txtValorVenda1;
    // End of variables declaration//GEN-END:variables
}
